name: Lobby
version: '${project.version}'
main: au.chival.lobby.Main
api-version: 1.8.8

commands:
  cosmetic:
    description: /cosmetic
    aliases: c
  profile:
    description: /profile
    aliases: p
  tptohub1:
    description: /setspawn
    aliases: ss

permissions:
  chiva.lobby.profile:
    default: true
  chiva.lobby.setspawn:
    default: true