name: Lobby
version: '${project.version}'
main: au.chival.lobby.Main
api-version: 1.8.8
commands:
  cosmetics:
    description: /cosmetic
    aliases: c
  profile:
    description: /profile
    aliases: p

permissions:
  chiva.lobby.profile:
    default: true