name: Lobby
version: '${project.version}'
main: au.chival.lobby.Main
api-version: 1.8.8
load: POSTWORLD

commands:
  cosmetic:
    description: /cosmetic
    aliases: c
  profile:
    description: /profile
    aliases: p
  setspawn:
    description: /setspawn
    aliases: ss

permissions:
  chiva.lobby.setspawn:
    default: true
  chival.lobby.adminboard:
    default: false