name: Lobby
version: '${project.version}'
main: au.chival.lobby.Main
api-version: 1.8.8
load: POSTWORLD

commands:
  cosmetic:
    description: /cosmetic
    aliases: c
  profile:
    description: /profile
    aliases: p
  setspawn:
    description: /setspawn
    aliases: ss
  spawn:
    description: /spawn
    aliases: s

permissions:
  chival.lobby.setspawn:
    default: false
  chival.lobby.adminboard:
    default: false
  chival.lobby.build:
    default: false
  chival.lobby.spawn-other:
    default: false